env:
  name: "LunarLander-v3"
  continuous: false
  gravity: -10.0
  enable_wind: false
  wind_power: 15.0
  turbulence_power: 1.5
  seed: 0

eval:
  episodes: 100

policy:
  type: "DQN"
  hidden_sizes: [64, 128, 64]

name: "secondConfig"